name: arc prerelease deployment test

on:
  release:
    types: [prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: ./examples/arc-prerelease-deployment-test

      - run: npm run test:e2e:run
        working-directory: ./examples/arc-prerelease-deployment-test

      - name: Build
        run: npm run build
        working-directory: ./examples/arc-prerelease-deployment-test

      - name: Install Arc CLI
        run: npm i -g @architect/architect
        working-directory: ./examples/arc-prerelease-deployment-test

      - name: Deploy to Arc
        run: arc deploy
        working-directory: ./examples/arc-prerelease-deployment-test
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
