name: netlify prerelease deployment test

on:
  release:
    types: [prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
        working-directory: ./examples/netlify-prerelease-deployment-test

      - run: npm run test:e2e:run
        working-directory: ./examples/netlify-prerelease-deployment-test

      - run: npm run build
        working-directory: ./examples/netlify-prerelease-deployment-test

      - name: Create Netlify Site
        working-directory: ./examples/netlify-prerelease-deployment-test
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.TEST_NETLIFY_TOKEN }}
        run: node ./deploy.mjs
