name: vercel prerelease deployment test

on:
  release:
    types: [prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
        working-directory: ./examples/vercel-prerelease-deployment-test

      - run: npm run test:e2e:run
        working-directory: ./examples/vercel-prerelease-deployment-test

      - run: npm run build
        working-directory: ./examples/vercel-prerelease-deployment-test

      - name: Create Vercel Site
        working-directory: ./examples/vercel-prerelease-deployment-test
        env:
          VERCEL_TOKEN: ${{ secrets.TEST_VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.TEST_VERCEL_USER_ID }}
        run: node ./deploy.mjs
